apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace  }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: "k8s-hello-node"
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      tolerations:
        - key: app
          operator: Equal
          value: node
          effect: NoSchedule
